server:
  port: 9800
#  ssl:
#    key-store: classpath:sixkey-world.top.jks
#    key-store-type: JKS
#    key-store-password: 6572954g4m1
#
#mybatis-plus:
#  type-enums-package: com.qs.enums
##  configuration:
##    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: is_delete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#
#spring:
#  servlet:
#    multipart:
#      max-file-size: 20MB
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/datasource?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
#  redis:
#    database: 0
#    host: host
#    password: 123456
#    port: 6379
#    time-to-live: 1800000
#    lettuce:
#      pool:
#        max-active: 20 #最大连接数
#        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
#        max-idle: 5    #最大空闲
#        min-idle: 0     #最小空闲
#  elasticsearch:
#    uris: http://host:9200
#    # 连接超时时间（默认1s）
#    connection-timeout: 10s
#
##阿里云上传头像图片
#oss:
#  endpoint: oss-cn
#  accessKey: LTAI5tC
#  secretKey: Ie9HxEAPRql
#  bucketName: sixkey
#
#sa-token:
#  # token 名称（同时也是 cookie 名称）
#  token-name: authorization
#  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
#  timeout: -1
#  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
#  active-timeout: -1
#  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
#  is-concurrent: false
#  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
#  is-share: true
#  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
#  token-style: uuid
#  # 是否输出操作日志
#  is-log: true